# -*- coding: utf-8 -*-
"""add.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpYfudu3NOc3bdNbfUdxo_QFZqvHdCeX
"""

# Function to add two numbers
def add_two_numbers(a, b):
    return a + b

# Example usage
num1 = 5
num2 = 7

result = add_two_numbers(num1, num2)
print(f"The sum of {num1} and {num2} is {result}")

