# -*- coding: utf-8 -*-
"""add.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpYfudu3NOc3bdNbfUdxo_QFZqvHdCeX
"""

# Function to add two numbers
def add_three_numbers(a, b,c):
    return a + b

# Example usage
num1 = 5
num2 = 7
num3 = 4

result = add_two_numbers(num1, num2,num3)
print(f"The sum of {num1} ,{num2} and { num3} is {result}")

