# -*- coding: utf-8 -*-
"""addition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RMLe39o51Gb2YMMoarNvjSGJUHACFx2
"""

# Define two numbers
num1 = 5
num2 = 3

# Add the numbers
sum = num1 + num2

# Print the result
print("The sum of", num1, "and", num2, "is", sum)