# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxEphRqlLZRCL6l-3m6mw-bKt1Ev5hMt
"""

# Print "Hello, World!" to the console
print("Hello, World!")