# -*- coding: utf-8 -*-
"""sum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNtc8KdBfiem28Ivst_Kw30IikyOqPW-
"""

a = 12
b = 15
sum = a+b
print(sum)

